// <auto-generated />
using System;
using DO_AN.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DO_AN.Migrations
{
    [DbContext(typeof(DOANContext))]
    [Migration("20240626034625_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DO_AN.Models.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Account");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("ID_Role");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Sex")
                        .HasColumnType("bit");

                    b.HasKey("IdAccount");

                    b.HasIndex(new[] { "IdRole" }, "IX_Account_ID_Role");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Coach", b =>
                {
                    b.Property<int>("IdCoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Coach");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoach"), 1L, 1);

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdSeat")
                        .HasColumnType("int")
                        .HasColumnName("ID_Seat");

                    b.Property<string>("NameCoach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name_Coach");

                    b.Property<int?>("SeatsQuantity")
                        .HasColumnType("int")
                        .HasColumnName("Seats_Quantity");

                    b.HasKey("IdCoach");

                    b.HasIndex(new[] { "IdSeat" }, "IX_Coach_ID_Seat");

                    b.ToTable("Coach", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Customer", b =>
                {
                    b.Property<int>("IdCus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Cus");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCus"), 1L, 1);

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Full_Name");

                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("ID_Account");

                    b.Property<int?>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("ID_Order");

                    b.HasKey("IdCus");

                    b.HasIndex(new[] { "IdAccount" }, "IX_Customer_ID_Account");

                    b.HasIndex(new[] { "IdOrder" }, "IX_Customer_ID_Order");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Discount", b =>
                {
                    b.Property<int>("IdDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Discount");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiscount"), 1L, 1);

                    b.Property<string>("Information")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameDiscount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name_Discount");

                    b.Property<int?>("PercentDiscount")
                        .HasColumnType("int")
                        .HasColumnName("Percent_Discount");

                    b.HasKey("IdDiscount");

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Order");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"), 1L, 1);

                    b.Property<DateTime?>("DateOrder")
                        .HasColumnType("date")
                        .HasColumnName("Date_Order");

                    b.Property<int?>("IdDiscount")
                        .HasColumnType("int")
                        .HasColumnName("ID_Discount");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int")
                        .HasColumnName("ID_Ticket");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("Unit_Price");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdDiscount");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.OrderTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("ID_Order");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int")
                        .HasColumnName("ID_Ticket");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdOrder" }, "IX_Order_Ticket_ID_Order");

                    b.HasIndex(new[] { "IdTicket" }, "IX_Order_Ticket_ID_Ticket");

                    b.ToTable("Order_Ticket", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Role");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"), 1L, 1);

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name_Role");

                    b.HasKey("IdRole");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Seat", b =>
                {
                    b.Property<int>("IdSeat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Seat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeat"), 1L, 1);

                    b.Property<string>("NameSeat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name_Seat");

                    b.Property<bool?>("State")
                        .HasColumnType("bit");

                    b.HasKey("IdSeat");

                    b.ToTable("Seat", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Ticket");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<int>("IdSeat")
                        .HasColumnType("int")
                        .HasColumnName("ID_Seat");

                    b.Property<int>("IdTrain")
                        .HasColumnType("int")
                        .HasColumnName("ID_Train");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("IdTicket");

                    b.HasIndex(new[] { "IdSeat" }, "IX_Ticket_ID_Seat");

                    b.HasIndex(new[] { "IdTrain" }, "IX_Ticket_ID_Train");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Train", b =>
                {
                    b.Property<int>("IdTrain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Train");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrain"), 1L, 1);

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("date")
                        .HasColumnName("Date_End");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("date")
                        .HasColumnName("Date_Start");

                    b.Property<int>("IdCoach")
                        .HasColumnType("int")
                        .HasColumnName("ID_Coach");

                    b.Property<int>("IdTrainRoute")
                        .HasColumnType("int")
                        .HasColumnName("ID_TrainRoute");

                    b.Property<string>("NameTrain")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name_Train");

                    b.HasKey("IdTrain");

                    b.HasIndex(new[] { "IdCoach" }, "IX_Train_ID_Coach");

                    b.HasIndex(new[] { "IdTrainRoute" }, "IX_Train_ID_TrainRoute");

                    b.ToTable("Train", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.TrainRoute", b =>
                {
                    b.Property<int>("IdTrainRoute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TrainRoute");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrainRoute"), 1L, 1);

                    b.Property<string>("NameTrainRoute")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name_TrainRoute");

                    b.HasKey("IdTrainRoute");

                    b.ToTable("TrainRoute", (string)null);
                });

            modelBuilder.Entity("DO_AN.Models.Account", b =>
                {
                    b.HasOne("DO_AN.Models.Role", "IdRoleNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Role");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("DO_AN.Models.Coach", b =>
                {
                    b.HasOne("DO_AN.Models.Seat", "IdSeatNavigation")
                        .WithMany("Coaches")
                        .HasForeignKey("IdSeat")
                        .HasConstraintName("FK_Coach_Seat");

                    b.Navigation("IdSeatNavigation");
                });

            modelBuilder.Entity("DO_AN.Models.Customer", b =>
                {
                    b.HasOne("DO_AN.Models.Account", "IdAccountNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("IdAccount")
                        .IsRequired()
                        .HasConstraintName("FK_Customer_Account");

                    b.HasOne("DO_AN.Models.Order", "IdOrderNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK_Customer_Order");

                    b.Navigation("IdAccountNavigation");

                    b.Navigation("IdOrderNavigation");
                });

            modelBuilder.Entity("DO_AN.Models.Order", b =>
                {
                    b.HasOne("DO_AN.Models.Discount", "IdDiscountNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdDiscount")
                        .HasConstraintName("FK_Order_Discount");

                    b.Navigation("IdDiscountNavigation");
                });

            modelBuilder.Entity("DO_AN.Models.OrderTicket", b =>
                {
                    b.HasOne("DO_AN.Models.Order", "IdOrderNavigation")
                        .WithMany("OrderTickets")
                        .HasForeignKey("IdOrder")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Ticket_Order");

                    b.HasOne("DO_AN.Models.Ticket", "IdTicketNavigation")
                        .WithMany("OrderTickets")
                        .HasForeignKey("IdTicket")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Ticket_Ticket");

                    b.Navigation("IdOrderNavigation");

                    b.Navigation("IdTicketNavigation");
                });

            modelBuilder.Entity("DO_AN.Models.Ticket", b =>
                {
                    b.HasOne("DO_AN.Models.Seat", "IdSeatNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdSeat")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Seat");

                    b.HasOne("DO_AN.Models.Train", "IdTrainNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdTrain")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Train");

                    b.Navigation("IdSeatNavigation");

                    b.Navigation("IdTrainNavigation");
                });

            modelBuilder.Entity("DO_AN.Models.Train", b =>
                {
                    b.HasOne("DO_AN.Models.Coach", "IdCoachNavigation")
                        .WithMany("Trains")
                        .HasForeignKey("IdCoach")
                        .IsRequired()
                        .HasConstraintName("FK_Train_Coach");

                    b.HasOne("DO_AN.Models.TrainRoute", "IdTrainRouteNavigation")
                        .WithMany("Trains")
                        .HasForeignKey("IdTrainRoute")
                        .IsRequired()
                        .HasConstraintName("FK_Train_TrainRoute");

                    b.Navigation("IdCoachNavigation");

                    b.Navigation("IdTrainRouteNavigation");
                });

            modelBuilder.Entity("DO_AN.Models.Account", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("DO_AN.Models.Coach", b =>
                {
                    b.Navigation("Trains");
                });

            modelBuilder.Entity("DO_AN.Models.Discount", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DO_AN.Models.Order", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("OrderTickets");
                });

            modelBuilder.Entity("DO_AN.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("DO_AN.Models.Seat", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DO_AN.Models.Ticket", b =>
                {
                    b.Navigation("OrderTickets");
                });

            modelBuilder.Entity("DO_AN.Models.Train", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DO_AN.Models.TrainRoute", b =>
                {
                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
